- name: Create helper image BuildConfig from template
  template:
    src: "{{ utils_helper_image_buildconfig }}"
    dest: "{{ artifact_extra_logs_dir }}/helper.yml"
    mode: 0400

- name: Apply helper image BuildConfig
  command: oc apply -f "{{ artifact_extra_logs_dir }}/helper.yml"

- name: Get the name of the helper build
  command:
    oc get builds
        -lbuildconfig={{ local_image_name }}-helper
        -oname
        -n utils-ci
  register: helper_name_cmd
  failed_when: helper_name_cmd.stdout | length == 0

- name: Await and log helper image build completion
  block:
  - name: Wait for the helper image to be built
    command:
      oc get {{ helper_name_cmd.stdout }}
          -ojsonpath={.status.phase}
          -n utils-ci
    register: wait_helper_build
    until: "'Complete' in wait_helper_build.stdout or 'Failed' in wait_helper_build.stdout"
    retries: 40
    delay: 30

  - name: Fail if the helper image failed to be built
    when: "'Failed' in wait_helper_build.stdout"
    fail: msg="The helper image failed to build"

  always:
  - name: Store the logs of helper image build (debug)
    shell:
      oc logs {{ helper_name_cmd.stdout }} -n utils-ci > {{ artifact_extra_logs_dir }}/image-helper-build.log
    failed_when: false
