- name: Check that local_image_name is defined
  fail: msg="Bailing out. This play requires 'local_image_name'"
  when: local_image_name is undefined

- name: Check that image_tag is defined
  fail: msg="Bailing out. This play requires 'image_tag'"
  when: image_tag is undefined

- name: Check that memory is defined
  fail: msg="Bailing out. This play requires 'memory'"
  when: memory is undefined

- name: Create build config from template
  command: 
    /bin/bash "{{ utils_create_build_config_script }}" 
      -n "{{ local_image_name }}"
      -t "{{ image_tag }}"
      -d "{{ docker_path }}"
      -g "{{ git_repo }}"
      -p "{{ git_path }}"
      -b "{{ branch }}"
      -m "{{ memory }}"
      -o "{{ artifact_extra_logs_dir }}"

- name: Create namespace for images if doesn't exist
  shell: kubectl create namespace utils-ci --dry-run=client -o yaml | kubectl apply -f -

- name: Create imagestream for image if doesn't exist
  command: oc create imagestream {{ local_image_name }} --namespace=utils-ci
  failed_when: false

- name: Delete old image build config if exists
  command: oc delete -f "{{ artifact_extra_logs_dir }}/config.yml"
  failed_when: false

- name: Apply image build config
  command: oc apply -f "{{ artifact_extra_logs_dir }}/config.yml"

- name: Get the name of the build
  command:
    oc get builds
        -lbuildconfig={{ local_image_name }}
        -oname
        -n utils-ci
  register: build_name_cmd
  failed_when: build_name_cmd.stdout | length == 0

- name: Get build config description
  command: oc describe --namespace=utils-ci bc/{{ local_image_name }}
  register: build_config_desc
  failed_when: build_config_desc.stdout | length == 0

- block:
  - name: Wait for the image to be built
    command:
      oc get {{ build_name_cmd.stdout }}
          -ojsonpath={.status.phase}
          -n utils-ci
    register: wait_img_build
    until: "'Complete' in wait_img_build.stdout or 'Failed' in wait_img_build.stdout"
    retries: 40
    delay: 30

  - name: Fail if the image failed to be built
    when: "'Failed' in wait_img_build.stdout"
    fail: msg="The image failed to build"

  always:
  - name: Get build config description (again)
    command: oc describe --namespace=utils-ci bc/{{ local_image_name }}
    register: build_config_desc_post
    failed_when: build_config_desc_post.stdout | length == 0

  - name: Store the logs of image build (debug)
    shell:
      oc logs {{ build_name_cmd.stdout }} -n utils-ci > {{ artifact_extra_logs_dir }}/image-build.log
    failed_when: false

- name: Create helper image build config from template
  template:
    src: "{{ utils_helper_image_build_config }}"
    dest: "{{ artifact_extra_logs_dir }}/helper.yml"
    mode: 0400

- name: Apply helper image build config
  command: oc apply -f "{{ artifact_extra_logs_dir }}/helper.yml"

- name: Get the name of the helper build
  command:
    oc get builds
        -lbuildconfig={{ local_image_name }}-helper
        -oname
        -n utils-ci
  register: helper_name_cmd
  failed_when: helper_name_cmd.stdout | length == 0

- block:
  - name: Wait for the helper image to be built
    command:
      oc get {{ helper_name_cmd.stdout }}
          -ojsonpath={.status.phase}
          -n utils-ci
    register: wait_helper_build
    until: "'Complete' in wait_helper_build.stdout or 'Failed' in wait_helper_build.stdout"
    retries: 40
    delay: 30

  - name: Fail if the helper image failed to be built
    when: "'Failed' in wait_helper_build.stdout"
    fail: msg="The helper image failed to build"

  always:
  - name: Store the logs of helper image build (debug)
    shell:
      oc logs {{ helper_name_cmd.stdout }} -n utils-ci > {{ artifact_extra_logs_dir }}/image-helper-build.log
    failed_when: false
